### ISSUE TITLE
use npm pack

### ISSUE THREAD

**Issue by juliangruber** [repo-utils/npm-download#1]
see https://github.com/segmentio/npm-diff/issues/1

**Comment by jonathanong** [comment]
oh shit. i read that wrong. it hought you wanted me to use npm-diff. meh, i think just straight `curl | tar` is easier. trying to avoid deps.

what's the benefit? private npm registries maybe?

**Comment by juliangruber** [comment]
it will always work, what you (and also still npm-diff) currently are doing is like relying on undocumented node internals

**Comment by juliangruber** [comment]
- it works with custom registries and all your .npmrc stuff

**Comment by jonathanong** [comment]
ah ok. custom registries. good enough reason for me. need that for github as well. WOO HOO API CALLS
